const PRESET_TEMPLATES = [
  // ==================== DIWALI ====================
  {
    id: 'diwali-poster',
    name: 'Diwali Safe & Health Poster',
    category: 'Diwali · Poster Infographic',
    festival: 'Diwali',
    styleType: 'poster',
    badge: 'HEALTH & SAFETY POSTER',
    subtitle: 'Celebrate Safe, Healthy & Happy',
    tagline: 'Light up happiness, not pollution. Choose safety. Choose health.',
    pillars: [
      { icon: '🛡️', title: 'PREVENT', desc: 'Burns & Fire' },
      { icon: '👂', title: 'PROTECT', desc: 'Your Hearing' },
      { icon: '🍃', title: 'BREATHE', desc: 'Clean Air' },
      { icon: '🥗', title: 'EAT RIGHT', desc: 'Enjoy Sweets' }
    ],
    background: 'linear-gradient(175deg, #180928 0%, #35104a 45%, #fff9f0 45.1%, #fff9f0 100%)',
    headerBg: 'linear-gradient(135deg, #180928, #3b0f55)',
    bodyBg: '#fffaf3',
    colors: ['#180928', '#ffaa00'],
    textColor: '#1e112a',
    headerTextColor: '#ffeedd',
    accentColor: '#d97706',
    font: 'sans',
    stickers: ['🪔', '✨', '🎆', '🌟'],
    shape: 'soft',
    border: '#f59e0b',
    panel: true,
    festivals: ['Diwali']
  },
  {
    id: 'diwali-royal',
    name: 'Diwali Royal Deepawali',
    category: 'Diwali · Luxury & Gold',
    festival: 'Diwali',
    styleType: 'royal',
    badge: 'ROYAL ILLUMINATION',
    subtitle: 'Festival of Divine Lights & Prosperity',
    tagline: 'May golden lamps illuminate every corner of your home and heart.',
    background: 'radial-gradient(ellipse at 50% 25%, #4a192c 0%, #170414 70%, #0c020b 100%)',
    colors: ['#300d1d', '#facc15'],
    textColor: '#fef3c7',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🪔', '✨', '👑', '🪔'],
    shape: 'circle',
    border: '#d97706',
    panel: true,
    festivals: ['Diwali']
  },
  {
    id: 'diwali-vibrant',
    name: 'Diwali Rangoli & Spark',
    category: 'Diwali · Festive Amber',
    festival: 'Diwali',
    styleType: 'vibrant',
    badge: 'FESTIVE GLOW',
    subtitle: 'Joyous Auspicious Celebrations',
    tagline: 'Sparkling lights, joyous moments, sweet blessings.',
    background: 'linear-gradient(145deg, #851d18 0%, #b45309 50%, #fef3c7 100%)',
    colors: ['#851d18', '#fef3c7'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#b45309',
    font: 'serif',
    stickers: ['🪔', '🎆', '🌸', '✨'],
    shape: 'soft',
    border: '#fbbf24',
    festivals: ['Diwali']
  },
  {
    id: 'diwali-minimal',
    name: 'Diwali Serene Warmth',
    category: 'Diwali · Clean & Pastel',
    festival: 'Diwali',
    styleType: 'minimal',
    badge: 'PEACE & LIGHT',
    subtitle: 'Warm Wishes & Blessings',
    tagline: 'A gentle glow of gratitude and peace.',
    background: 'linear-gradient(135deg, #fff7ed 0%, #ffedd5 50%, #fed7aa 100%)',
    colors: ['#fff7ed', '#fed7aa'],
    textColor: '#7c2d12',
    headerTextColor: '#7c2d12',
    accentColor: '#ea580c',
    font: 'serif',
    stickers: ['🪔', '🕊️', '✨', '💛'],
    shape: 'circle',
    border: '#f97316',
    festivals: ['Diwali']
  },

  // ==================== HOLI ====================
  {
    id: 'holi-poster',
    name: 'Holi Play Safe & Stay Healthy',
    category: 'Holi · Poster Infographic',
    festival: 'Holi',
    styleType: 'poster',
    badge: 'HEALTH & SAFETY POSTER',
    subtitle: 'Play Safe, Stay Healthy',
    tagline: 'Let the colors of Holi bring joy, not harm. Celebrate with care!',
    pillars: [
      { icon: '🧴', title: 'PROTECT', desc: 'Your Skin' },
      { icon: '👓', title: 'PROTECT', desc: 'Your Eyes' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🤝', title: 'PLAY SAFE', desc: 'Be Respectful' }
    ],
    background: 'linear-gradient(175deg, #ec4899 0%, #8b5cf6 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #db2777, #7c3aed)',
    bodyBg: '#fffdfa',
    colors: ['#db2777', '#06b6d4'],
    textColor: '#3b0764',
    headerTextColor: '#ffffff',
    accentColor: '#ec4899',
    font: 'sans',
    stickers: ['🌈', '🎉', '🌸', '✨'],
    shape: 'heavy',
    border: '#a855f7',
    panel: true,
    festivals: ['Holi']
  },
  {
    id: 'holi-vibrant',
    name: 'Holi Gulal Explosion',
    category: 'Holi · Ultra Vibrant Splash',
    festival: 'Holi',
    styleType: 'vibrant',
    badge: 'COLOR CARNIVAL',
    subtitle: 'Rang Barse — Joy & Laughter',
    tagline: 'Drenched in friendship, colors, and pure happiness.',
    background: 'radial-gradient(circle at 80% 20%, #f43f5e 0%, #ec4899 30%, #8b5cf6 65%, #06b6d4 100%)',
    colors: ['#f43f5e', '#06b6d4'],
    textColor: '#ffffff',
    headerTextColor: '#ffffff',
    accentColor: '#fde047',
    font: 'display',
    stickers: ['🎨', '💦', '🌈', '🥳'],
    shape: 'pill',
    border: '#f43f5e',
    festivals: ['Holi']
  },
  {
    id: 'holi-spring',
    name: 'Holi Pastel Spring Glow',
    category: 'Holi · Organic & Spring',
    festival: 'Holi',
    styleType: 'minimal',
    badge: 'SPRING HARMONY',
    subtitle: 'Organic Colours, Endless Joy',
    tagline: 'May your life bloom in shades of love and smiles.',
    background: 'linear-gradient(135deg, #fdf4ff 0%, #fae8ff 40%, #e0f2fe 100%)',
    colors: ['#fdf4ff', '#e0f2fe'],
    textColor: '#701a75',
    headerTextColor: '#701a75',
    accentColor: '#c026d3',
    font: 'sans',
    stickers: ['🌸', '✨', '💛', '🌈'],
    shape: 'soft',
    border: '#d946ef',
    festivals: ['Holi']
  },

  // ==================== NAVRATRI ====================
  {
    id: 'navratri-poster',
    name: 'Navratri Dance & Good Health',
    category: 'Navratri · Poster Infographic',
    festival: 'Navratri',
    styleType: 'poster',
    badge: 'GARBA & WELLNESS POSTER',
    subtitle: 'Dance • Devotion • Good Health',
    tagline: 'Enjoy every step. Stay active. Stay healthy.',
    pillars: [
      { icon: '🏃', title: 'WARM UP', desc: 'Before Dance' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '👟', title: 'WEAR', desc: 'Right Footwear' },
      { icon: '🛌', title: 'REST &', desc: 'Recover Well' }
    ],
    background: 'linear-gradient(175deg, #4c0519 0%, #831843 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #4c0519, #9d174d)',
    bodyBg: '#fffdfa',
    colors: ['#4c0519', '#fbbf24'],
    textColor: '#3b0764',
    headerTextColor: '#fef3c7',
    accentColor: '#db2777',
    font: 'sans',
    stickers: ['💃', '🪔', '✨', '🌸'],
    shape: 'circle',
    border: '#f59e0b',
    panel: true,
    festivals: ['Navratri']
  },
  {
    id: 'navratri-royal',
    name: 'Navratri Garba Raas Glow',
    category: 'Navratri · Royal Garba',
    festival: 'Navratri',
    styleType: 'royal',
    badge: 'DANDIYA NIGHTS',
    subtitle: 'Nine Nights of Divine Radiance',
    tagline: 'Whirling beats, joyful smiles, and Durga Maa blessings.',
    background: 'linear-gradient(145deg, #2e1065 0%, #581c87 50%, #9333ea 100%)',
    colors: ['#2e1065', '#9333ea'],
    textColor: '#fdf4ff',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🪔', '💃', '✨', '🥁'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['Navratri']
  },
  {
    id: 'navratri-shakti',
    name: 'Navratri Maa Shakti Blessings',
    category: 'Navratri · Auspicious Vermilion',
    festival: 'Navratri',
    styleType: 'vibrant',
    badge: 'DIVINE BLESSINGS',
    subtitle: 'Strength, Grace & Devotion',
    tagline: 'May Goddess Durga shower prosperity and divine energy.',
    background: 'linear-gradient(135deg, #991b1b 0%, #dc2626 50%, #f97316 100%)',
    colors: ['#991b1b', '#f97316'],
    textColor: '#fff7ed',
    headerTextColor: '#fef08a',
    accentColor: '#fbbf24',
    font: 'serif',
    stickers: ['🌺', '🪔', '✨', '👑'],
    shape: 'square',
    border: '#fde047',
    festivals: ['Navratri']
  },

  // ==================== UTTARAYAN ====================
  {
    id: 'uttarayan-poster',
    name: 'Uttarayan Fly High, Stay Safe',
    category: 'Uttarayan · Poster Infographic',
    festival: 'Uttarayan / Makar Sankranti',
    styleType: 'poster',
    badge: 'KITE FESTIVAL & SAFETY',
    subtitle: 'Fly High, Stay Safe',
    tagline: 'Enjoy the sky. Protect your health.',
    pillars: [
      { icon: '🧢', title: 'PROTECT', desc: 'From Sun & UV' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🏢', title: 'BE SAFE', desc: 'On Terrace' },
      { icon: '🕊️', title: 'PROTECT', desc: 'Eyes & Birds' }
    ],
    background: 'linear-gradient(175deg, #0284c7 0%, #0369a1 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #0284c7, #075985)',
    bodyBg: '#fffdfa',
    colors: ['#0284c7', '#fbbf24'],
    textColor: '#0c4a6e',
    headerTextColor: '#f0f9ff',
    accentColor: '#0284c7',
    font: 'sans',
    stickers: ['🪁', '☀️', '🎉', '✨'],
    shape: 'soft',
    border: '#38bdf8',
    panel: true,
    festivals: ['Uttarayan / Makar Sankranti']
  },
  {
    id: 'uttarayan-azure',
    name: 'Uttarayan Azure Sky Carnival',
    category: 'Uttarayan · Sky & Kites',
    festival: 'Uttarayan / Makar Sankranti',
    styleType: 'vibrant',
    badge: 'KAI PO CHE',
    subtitle: 'Soaring Hopes, Unlimited Joy',
    tagline: 'Loud cheers, colorful skies, and chikki sweetness.',
    background: 'linear-gradient(160deg, #38bdf8 0%, #e0f2fe 50%, #fed7aa 100%)',
    colors: ['#38bdf8', '#fed7aa'],
    textColor: '#075985',
    headerTextColor: '#0c4a6e',
    accentColor: '#f97316',
    font: 'sans',
    stickers: ['🪁', '☀️', '🪁', '✨'],
    shape: 'pill',
    border: '#0284c7',
    festivals: ['Uttarayan / Makar Sankranti']
  },
  {
    id: 'uttarayan-harvest',
    name: 'Makar Sankranti Golden Harvest',
    category: 'Uttarayan · Warm Harvest',
    festival: 'Uttarayan / Makar Sankranti',
    styleType: 'royal',
    badge: 'HARVEST BLESSINGS',
    subtitle: 'Til-Gul & Sunshine Warmth',
    tagline: 'May this Sankranti bring prosperity and golden harvest.',
    background: 'linear-gradient(145deg, #b45309 0%, #d97706 50%, #fef3c7 100%)',
    colors: ['#b45309', '#fef3c7'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#b45309',
    font: 'serif',
    stickers: ['🌾', '☀️', '🪁', '✨'],
    shape: 'circle',
    border: '#f59e0b',
    festivals: ['Uttarayan / Makar Sankranti']
  },

  // ==================== RAKSHA BANDHAN ====================
  {
    id: 'rakhi-poster',
    name: 'Raksha Bandhan A Bond That Cares',
    category: 'Raksha Bandhan · Poster Infographic',
    festival: 'Raksha Bandhan',
    styleType: 'poster',
    badge: 'HEALTH & BONDING POSTER',
    subtitle: 'A Bond That Cares',
    tagline: 'A thread of love. A promise of health and protection.',
    pillars: [
      { icon: '🤝', title: 'CARE', desc: 'For Each Other' },
      { icon: '🥗', title: 'EAT', desc: 'Healthy Together' },
      { icon: '🏃', title: 'STAY', desc: 'Active & Fit' },
      { icon: '❤️', title: 'SUPPORT', desc: 'Always & Forever' }
    ],
    background: 'linear-gradient(175deg, #7c2d12 0%, #9a3412 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #7c2d12, #c2410c)',
    bodyBg: '#fffdfa',
    colors: ['#7c2d12', '#f97316'],
    textColor: '#431407',
    headerTextColor: '#ffedd5',
    accentColor: '#ea580c',
    font: 'sans',
    stickers: ['🪔', '✨', '🌸', '🪔'],
    shape: 'circle',
    border: '#ea580c',
    panel: true,
    festivals: ['Raksha Bandhan']
  },
  {
    id: 'rakhi-royal',
    name: 'Raksha Bandhan Sacred Threads',
    category: 'Raksha Bandhan · Royal Traditional',
    festival: 'Raksha Bandhan',
    styleType: 'royal',
    badge: 'SACRED BOND',
    subtitle: 'Lifelong Love & Protection',
    tagline: 'May this pious thread safeguard happiness forever.',
    background: 'linear-gradient(135deg, #fff7ed 0%, #fed7aa 60%, #fca5a5 100%)',
    colors: ['#fff7ed', '#fca5a5'],
    textColor: '#7f1d1d',
    headerTextColor: '#991b1b',
    accentColor: '#dc2626',
    font: 'serif',
    stickers: ['🪔', '✨', '🌺', '💖'],
    shape: 'soft',
    border: '#b45309',
    festivals: ['Raksha Bandhan']
  },
  {
    id: 'rakhi-floral',
    name: 'Rakhi Sibling Sweetness',
    category: 'Raksha Bandhan · Sweet Pastel',
    festival: 'Raksha Bandhan',
    styleType: 'minimal',
    badge: 'CHERISHED MEMORIES',
    subtitle: 'Always by Your Side',
    tagline: 'Growing up with you is the greatest gift.',
    background: 'linear-gradient(135deg, #fdf2f8 0%, #fce7f3 50%, #fbcfe8 100%)',
    colors: ['#fdf2f8', '#fbcfe8'],
    textColor: '#831843',
    headerTextColor: '#831843',
    accentColor: '#db2777',
    font: 'serif',
    stickers: ['🌸', '💕', '✨', '🎁'],
    shape: 'soft',
    border: '#ec4899',
    festivals: ['Raksha Bandhan']
  },

  // ==================== JANMASHTAMI ====================
  {
    id: 'janmashtami-poster',
    name: 'Janmashtami Joy & Healthy Devotion',
    category: 'Janmashtami · Poster Infographic',
    festival: 'Janmashtami',
    styleType: 'poster',
    badge: 'DEVOTION & HEALTH POSTER',
    subtitle: 'Celebrate with Joy, Stay Healthy',
    tagline: 'Let devotion bring happiness and good health.',
    pillars: [
      { icon: '🥛', title: 'EAT SAFE', desc: 'Keep Fasting Pure' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🥗', title: 'CHOOSE', desc: 'Healthy Fast Food' },
      { icon: '🧘', title: 'REST &', desc: 'Meditate' }
    ],
    background: 'linear-gradient(175deg, #1e3a8a 0%, #172554 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #1e3a8a, #1d4ed8)',
    bodyBg: '#fffdfa',
    colors: ['#1e3a8a', '#fbbf24'],
    textColor: '#172554',
    headerTextColor: '#eff6ff',
    accentColor: '#2563eb',
    font: 'sans',
    stickers: ['🪈', '🦚', '✨', '🌸'],
    shape: 'circle',
    border: '#2563eb',
    panel: true,
    festivals: ['Janmashtami']
  },
  {
    id: 'janmashtami-divine',
    name: 'Janmashtami Peacock Radiance',
    category: 'Janmashtami · Peacock Blue & Gold',
    festival: 'Janmashtami',
    styleType: 'royal',
    badge: 'DIVINE FLUTE',
    subtitle: 'Krishna Janmotsav Blessings',
    tagline: 'May Kanha bless your life with bliss, peace and divine melody.',
    background: 'radial-gradient(ellipse at center, #0f2b5c 0%, #081734 70%, #030a18 100%)',
    colors: ['#0f2b5c', '#030a18'],
    textColor: '#fef3c7',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🦚', '🪈', '✨', '👑'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['Janmashtami']
  },
  {
    id: 'janmashtami-makhan',
    name: 'Janmashtami Matki & Butter Glow',
    category: 'Janmashtami · Playful Krishna',
    festival: 'Janmashtami',
    styleType: 'vibrant',
    badge: 'MAKHAN CHOR',
    subtitle: 'Pure Devotion, Sweet Blessings',
    tagline: 'May the little Govinda steal all your worries and fill life with joy.',
    background: 'linear-gradient(145deg, #0284c7 0%, #38bdf8 50%, #fef08a 100%)',
    colors: ['#0284c7', '#fef08a'],
    textColor: '#075985',
    headerTextColor: '#ffffff',
    accentColor: '#0284c7',
    font: 'display',
    stickers: ['🪈', '🍯', '🦚', '✨'],
    shape: 'pill',
    border: '#38bdf8',
    festivals: ['Janmashtami']
  },

  // ==================== GANESH CHATURTHI ====================
  {
    id: 'ganesh-poster',
    name: 'Ganesh Chaturthi Responsible Poster',
    category: 'Ganesh Chaturthi · Poster Infographic',
    festival: 'Ganesh Chaturthi',
    styleType: 'poster',
    badge: 'ECO BAPPA & WELLNESS',
    subtitle: 'Celebrate Responsibly',
    tagline: 'Bappa says — stay healthy, stay happy!',
    pillars: [
      { icon: '🌱', title: 'CHOOSE', desc: 'Eco-Friendly Idols' },
      { icon: '🧹', title: 'KEEP', desc: 'Clean Everywhere' },
      { icon: '🥟', title: 'EAT', desc: 'Healthy Modaks' },
      { icon: '🛡️', title: 'STAY', desc: 'Safe in Crowds' }
    ],
    background: 'linear-gradient(175deg, #7c2d12 0%, #c2410c 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #7c2d12, #ea580c)',
    bodyBg: '#fffdfa',
    colors: ['#7c2d12', '#fbbf24'],
    textColor: '#431407',
    headerTextColor: '#fff7ed',
    accentColor: '#ea580c',
    font: 'sans',
    stickers: ['🐘', '🪔', '✨', '🌺'],
    shape: 'soft',
    border: '#f97316',
    panel: true,
    festivals: ['Ganesh Chaturthi']
  },
  {
    id: 'ganesh-royal',
    name: 'Ganesh Siddhivinayak Gold',
    category: 'Ganesh Chaturthi · Saffron & Crimson',
    festival: 'Ganesh Chaturthi',
    styleType: 'royal',
    badge: 'VIGHNAHARTA BLESSINGS',
    subtitle: 'Wisdom, Auspiciousness & Joy',
    tagline: 'May Lord Ganesha remove all obstacles and shower prosperity.',
    background: 'linear-gradient(145deg, #9a3412 0%, #ea580c 50%, #fef08a 100%)',
    colors: ['#9a3412', '#fef08a'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#ea580c',
    font: 'serif',
    stickers: ['🪔', '🌺', '✨', '👑'],
    shape: 'circle',
    border: '#f59e0b',
    festivals: ['Ganesh Chaturthi']
  },
  {
    id: 'ganesh-modak',
    name: 'Ganesh Mangal Murti Radiance',
    category: 'Ganesh Chaturthi · Marigold & Modak',
    festival: 'Ganesh Chaturthi',
    styleType: 'vibrant',
    badge: 'GANPATI BAPPA MORYA',
    subtitle: 'Auspicious Vibrancy & Prosperity',
    tagline: 'Singing, dancing, and heartfelt prayers for Lord Ganesha.',
    background: 'linear-gradient(135deg, #ea580c 0%, #facc15 60%, #fffbeb 100%)',
    colors: ['#ea580c', '#fffbeb'],
    textColor: '#7c2d12',
    headerTextColor: '#ffffff',
    accentColor: '#ea580c',
    font: 'serif',
    stickers: ['🐘', '🥟', '🪔', '✨'],
    shape: 'soft',
    border: '#ea580c',
    festivals: ['Ganesh Chaturthi']
  },

  // ==================== DUSSEHRA ====================
  {
    id: 'dussehra-poster',
    name: 'Dussehra Victory & Wellness Poster',
    category: 'Dussehra · Poster Infographic',
    festival: 'Dussehra',
    styleType: 'poster',
    badge: 'VICTORY OVER EVIL',
    subtitle: 'Victory of Good Over Evil',
    tagline: 'Let’s win over negativity and be the best version of ourselves.',
    pillars: [
      { icon: '🌱', title: 'CHOOSE', desc: 'Good Habits' },
      { icon: '🧘', title: 'MANAGE', desc: 'Stress & Stay Calm' },
      { icon: '💪', title: 'STAY', desc: 'Active & Strong' },
      { icon: '👨‍👩‍👧‍👦', title: 'SPEND TIME', desc: 'With Family' }
    ],
    background: 'linear-gradient(175deg, #831843 0%, #9f1239 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #831843, #be123c)',
    bodyBg: '#fffdfa',
    colors: ['#831843', '#facc15'],
    textColor: '#4c0519',
    headerTextColor: '#fff1f2',
    accentColor: '#e11d48',
    font: 'sans',
    stickers: ['🏹', '🪔', '✨', '🌟'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Dussehra']
  },
  {
    id: 'dussehra-royal',
    name: 'Dussehra Vijayadashami Glory',
    category: 'Dussehra · Warrior Amber',
    festival: 'Dussehra',
    styleType: 'royal',
    badge: 'TRIUMPH OF LIGHT',
    subtitle: 'Auspicious New Beginnings',
    tagline: 'May truth and righteousness guide your path to victory.',
    background: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 50%, #f59e0b 100%)',
    colors: ['#450a0a', '#f59e0b'],
    textColor: '#fef2f2',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🏹', '👑', '✨', '🪔'],
    shape: 'square',
    border: '#d97706',
    panel: true,
    festivals: ['Dussehra']
  },

  // ==================== BESTU VARAS ====================
  {
    id: 'bestuvaras-poster',
    name: 'Bestu Varas New Beginnings Poster',
    category: 'Bestu Varas · Poster Infographic',
    festival: 'Bestu Varas (Gujarati New Year)',
    styleType: 'poster',
    badge: 'GUJARATI NEW YEAR',
    subtitle: 'New Beginnings, Better Health',
    tagline: 'New year. New goals. A healthier, happier you.',
    pillars: [
      { icon: '🥗', title: 'EAT', desc: 'Balanced Diet' },
      { icon: '🏃', title: 'MOVE', desc: 'Daily & Stay Fit' },
      { icon: '✨', title: 'THINK', desc: 'Positive & Happy' },
      { icon: '📋', title: 'PLAN', desc: 'Your Health' }
    ],
    background: 'linear-gradient(175deg, #14532d 0%, #15803d 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #14532d, #16a34a)',
    bodyBg: '#fffdfa',
    colors: ['#14532d', '#facc15'],
    textColor: '#052e16',
    headerTextColor: '#f0fdf4',
    accentColor: '#16a34a',
    font: 'sans',
    stickers: ['🪔', '🌿', '✨', '🌸'],
    shape: 'circle',
    border: '#22c55e',
    panel: true,
    festivals: ['Bestu Varas (Gujarati New Year)']
  },
  {
    id: 'bestuvaras-royal',
    name: 'Nutan Varshabhinandan Gold',
    category: 'Bestu Varas · Auspicious Gold & Saffron',
    festival: 'Bestu Varas (Gujarati New Year)',
    styleType: 'royal',
    badge: 'NUTAN VARSHABHINANDAN',
    subtitle: 'Auspicious Gujarati New Year Wishes',
    tagline: 'May this year overflow with happiness, peace and success.',
    background: 'linear-gradient(145deg, #78350f 0%, #b45309 50%, #fef3c7 100%)',
    colors: ['#78350f', '#fef3c7'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#d97706',
    font: 'serif',
    stickers: ['🪔', '🌾', '✨', '👑'],
    shape: 'soft',
    border: '#f59e0b',
    festivals: ['Bestu Varas (Gujarati New Year)']
  },
  {
    id: 'bestuvaras-saal',
    name: 'Saal Mubarak Festive Toran',
    category: 'Bestu Varas · Marigold Toran',
    festival: 'Bestu Varas (Gujarati New Year)',
    styleType: 'vibrant',
    badge: 'SAAL MUBARAK',
    subtitle: 'Joyful Festive Greetings',
    tagline: 'Wishing you and your family a year of health, prosperity and smiles.',
    background: 'linear-gradient(135deg, #991b1b 0%, #ea580c 50%, #fde047 100%)',
    colors: ['#991b1b', '#fde047'],
    textColor: '#fff7ed',
    headerTextColor: '#fef08a',
    accentColor: '#fbbf24',
    font: 'serif',
    stickers: ['🪔', '🌺', '✨', '💛'],
    shape: 'soft',
    border: '#eab308',
    festivals: ['Bestu Varas (Gujarati New Year)']
  },

  // ==================== INDEPENDENCE & REPUBLIC DAY ====================
  {
    id: 'independence-poster',
    name: 'Independence Day Freedom & Health',
    category: 'Independence Day · Poster Infographic',
    festival: 'Independence Day',
    styleType: 'poster',
    badge: 'NATION & WELLNESS POSTER',
    subtitle: 'Freedom • Responsibility • Good Health',
    tagline: 'A healthy citizen makes a healthy India.',
    pillars: [
      { icon: '🏃', title: 'STAY', desc: 'Active & Energetic' },
      { icon: '🥗', title: 'EAT', desc: 'Balanced Food' },
      { icon: '🇮🇳', title: 'KEEP INDIA', desc: 'Clean & Green' },
      { icon: '🤝', title: 'CARE', desc: 'For All Citizens' }
    ],
    background: 'linear-gradient(175deg, #c2410c 0%, #15803d 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #ea580c, #16a34a)',
    bodyBg: '#fffdfa',
    colors: ['#ea580c', '#16a34a'],
    textColor: '#1e293b',
    headerTextColor: '#ffffff',
    accentColor: '#0284c7',
    font: 'sans',
    stickers: ['🇮🇳', '🕊️', '✨', '🌟'],
    shape: 'soft',
    border: '#0284c7',
    panel: true,
    festivals: ['Independence Day', 'Republic Day']
  },
  {
    id: 'independence-tricolor',
    name: 'Tricolor Pride & Glory',
    category: 'Independence Day · Tiranga Pride',
    festival: 'Independence Day',
    styleType: 'vibrant',
    badge: 'VANDE MATARAM',
    subtitle: 'Honour, Unity & Progress',
    tagline: 'Saluting our heritage and marching towards a brighter tomorrow.',
    background: 'linear-gradient(180deg, #ffedd5 0%, #ffffff 50%, #dcfce7 100%)',
    colors: ['#ea580c', '#16a34a'],
    textColor: '#0f172a',
    headerTextColor: '#0f172a',
    accentColor: '#1e3a8a',
    font: 'serif',
    stickers: ['🇮🇳', '🕊️', '✨', '💐'],
    shape: 'circle',
    border: '#1e3a8a',
    festivals: ['Independence Day', 'Republic Day']
  },

  // ==================== VALENTINE'S DAY ====================
  {
    id: 'valentines-poster',
    name: 'Valentine’s Connection & Wellbeing',
    category: 'Valentine\'s Day · Poster Infographic',
    festival: 'Valentine\'s Day',
    styleType: 'poster',
    badge: 'LOVE & WELLNESS POSTER',
    subtitle: 'Love • Connection • Wellbeing',
    tagline: 'Healthy relationships, happier life.',
    pillars: [
      { icon: '💬', title: 'CONNECT', desc: 'Talk & Listen' },
      { icon: '❤️', title: 'CARE', desc: 'For Each Other' },
      { icon: '⏳', title: 'SPEND TIME', desc: 'Together' },
      { icon: '🌸', title: 'BE KIND', desc: 'Every Day' }
    ],
    background: 'linear-gradient(175deg, #881337 0%, #be123c 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #881337, #e11d48)',
    bodyBg: '#fffdfa',
    colors: ['#881337', '#f43f5e'],
    textColor: '#4c0519',
    headerTextColor: '#ffe4e6',
    accentColor: '#e11d48',
    font: 'sans',
    stickers: ['❤️', '💕', '🌹', '✨'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Valentine\'s Day']
  },
  {
    id: 'valentines-romantic',
    name: 'Valentine Velvet Rose',
    category: 'Valentine\'s Day · Romantic Luxury',
    festival: 'Valentine\'s Day',
    styleType: 'royal',
    badge: 'ENDLESS LOVE',
    subtitle: 'Heart to Heart, Forever',
    tagline: 'You make every ordinary moment feel extraordinary.',
    background: 'linear-gradient(145deg, #4c0519 0%, #9f1239 50%, #fda4af 100%)',
    colors: ['#4c0519', '#fda4af'],
    textColor: '#ffe4e6',
    headerTextColor: '#ffffff',
    accentColor: '#fb7185',
    font: 'serif',
    stickers: ['🌹', '💖', '✨', '🥂'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Valentine\'s Day']
  },

  // ==================== CHRISTMAS ====================
  {
    id: 'christmas-poster',
    name: 'Christmas Joy & Health Poster',
    category: 'Christmas · Poster Infographic',
    festival: 'Christmas',
    styleType: 'poster',
    badge: 'HOLIDAY WELLNESS',
    subtitle: 'Joy • Peace • Good Health',
    tagline: 'Celebrate the season. Spread joy. Stay healthy.',
    pillars: [
      { icon: '🥗', title: 'EAT', desc: 'Mindfully & Light' },
      { icon: '🎁', title: 'SHARE', desc: 'Kindness & Love' },
      { icon: '🏃', title: 'STAY', desc: 'Active & Warm' },
      { icon: '🛌', title: 'REST', desc: 'Well & Recharge' }
    ],
    background: 'linear-gradient(175deg, #0f172a 0%, #1e293b 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #0f172a, #166534)',
    bodyBg: '#fffdfa',
    colors: ['#0f172a', '#166534'],
    textColor: '#0f172a',
    headerTextColor: '#f8fafc',
    accentColor: '#dc2626',
    font: 'sans',
    stickers: ['🎄', '⭐', '🎁', '✨'],
    shape: 'soft',
    border: '#22c55e',
    panel: true,
    festivals: ['Christmas']
  },
  {
    id: 'christmas-festive',
    name: 'Christmas Starry Pine',
    category: 'Christmas · Winter Magic',
    festival: 'Christmas',
    styleType: 'royal',
    badge: 'MERRY CHRISTMAS',
    subtitle: 'Warmth, Goodwill & Joy',
    tagline: 'May your holidays sparkle with moments of love and laughter.',
    background: 'radial-gradient(circle at 50% 30%, #166534 0%, #052e16 70%, #021a0d 100%)',
    colors: ['#166534', '#021a0d'],
    textColor: '#f0fdf4',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🎄', '⭐', '❄️', '✨'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['Christmas']
  },

  // ==================== EID ====================
  {
    id: 'eid-poster',
    name: 'Eid Mubarak Peace & Health',
    category: 'Eid · Poster Infographic',
    festival: 'Eid',
    styleType: 'poster',
    badge: 'PEACE & GRATITUDE',
    subtitle: 'Peace • Gratitude • Good Health',
    tagline: 'May Eid bring peace, gratitude and warm togetherness.',
    pillars: [
      { icon: '🤲', title: 'SHARE', desc: 'Blessings & Care' },
      { icon: '🥗', title: 'EAT', desc: 'Mindfully' },
      { icon: '👨‍👩‍👧‍👦', title: 'SPEND', desc: 'Family Time' },
      { icon: '✨', title: 'SPREAD', desc: 'Kindness Everywhere' }
    ],
    background: 'linear-gradient(175deg, #064e3b 0%, #047857 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #064e3b, #059669)',
    bodyBg: '#fffdfa',
    colors: ['#064e3b', '#facc15'],
    textColor: '#022c22',
    headerTextColor: '#ecfdf5',
    accentColor: '#059669',
    font: 'sans',
    stickers: ['🌙', '✨', '💐', '🤲'],
    shape: 'circle',
    border: '#10b981',
    panel: true,
    festivals: ['Eid']
  },
  {
    id: 'eid-crescent',
    name: 'Eid Royal Emerald & Gold',
    category: 'Eid · Luxury Emerald',
    festival: 'Eid',
    styleType: 'royal',
    badge: 'EID MUBARAK',
    subtitle: 'Abundant Blessings & Harmony',
    tagline: 'May divine light guide and bless you and your family.',
    background: 'linear-gradient(145deg, #022c22 0%, #064e3b 60%, #10b981 100%)',
    colors: ['#022c22', '#10b981'],
    textColor: '#ecfdf5',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🌙', '⭐', '✨', '🕌'],
    shape: 'soft',
    border: '#f59e0b',
    panel: true,
    festivals: ['Eid']
  },

  // ==================== NEW YEAR ====================
  {
    id: 'newyear-poster',
    name: 'New Year Goals & Health',
    category: 'New Year · Poster Infographic',
    festival: 'New Year',
    styleType: 'poster',
    badge: 'FRESH BEGINNINGS',
    subtitle: 'New Chapter • Fresh Goals • Better You',
    tagline: 'Step into the new year with vitality and joy.',
    pillars: [
      { icon: '🎯', title: 'SET', desc: 'Daily Habits' },
      { icon: '🏃', title: 'MOVE', desc: 'Every Single Day' },
      { icon: '🧠', title: 'STAY', desc: 'Mindful & Positive' },
      { icon: '💖', title: 'CHERISH', desc: 'Friends & Family' }
    ],
    background: 'linear-gradient(175deg, #18181b 0%, #27272a 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #09090b, #27272a)',
    bodyBg: '#fffdfa',
    colors: ['#18181b', '#facc15'],
    textColor: '#18181b',
    headerTextColor: '#fef08a',
    accentColor: '#eab308',
    font: 'sans',
    stickers: ['🎆', '🥂', '🌟', '✨'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['New Year']
  },
  {
    id: 'newyear-sparkle',
    name: 'New Year Midnight Radiance',
    category: 'New Year · Black & Gold Luxury',
    festival: 'New Year',
    styleType: 'royal',
    badge: 'HAPPY NEW YEAR',
    subtitle: 'Cheers to 365 New Chances',
    tagline: 'Wishing you limitless health, happiness and extraordinary success.',
    background: 'radial-gradient(circle at center, #1f1f2e 0%, #0d0d14 70%, #050508 100%)',
    colors: ['#1f1f2e', '#050508'],
    textColor: '#fef08a',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🎆', '🍾', '🥂', '✨'],
    shape: 'soft',
    border: '#f59e0b',
    panel: true,
    festivals: ['New Year']
  },

  // ==================== THANKSGIVING ====================
  {
    id: 'thanksgiving-poster',
    name: 'Thanksgiving Gratitude & Health',
    category: 'Thanksgiving · Poster Infographic',
    festival: 'Thanksgiving',
    styleType: 'poster',
    badge: 'GRATITUDE & WELLNESS',
    subtitle: 'Gratitude • Warmth • Wellbeing',
    tagline: 'Grateful hearts, healthy lives, joyful gatherings.',
    pillars: [
      { icon: '💛', title: 'SHARE', desc: 'Gratitude & Smiles' },
      { icon: '🥗', title: 'EAT', desc: 'Mindfully Together' },
      { icon: '🚶', title: 'WALK', desc: 'After Meals' },
      { icon: '👨‍👩‍👧‍👦', title: 'CHERISH', desc: 'Loved Ones' }
    ],
    background: 'linear-gradient(175deg, #78350f 0%, #9a3412 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #78350f, #c2410c)',
    bodyBg: '#fffdfa',
    colors: ['#78350f', '#f97316'],
    textColor: '#451a03',
    headerTextColor: '#fef3c7',
    accentColor: '#ea580c',
    font: 'sans',
    stickers: ['🍁', '🕯️', '💛', '✨'],
    shape: 'soft',
    border: '#ea580c',
    panel: true,
    festivals: ['Thanksgiving']
  },
  {
    id: 'thanksgiving-warm',
    name: 'Thanksgiving Golden Harvest',
    category: 'Thanksgiving · Autumn Warmth',
    festival: 'Thanksgiving',
    styleType: 'royal',
    badge: 'HARVEST BLESSINGS',
    subtitle: 'Count Your Blessings',
    tagline: 'May your table be filled with feast and your home with love.',
    background: 'linear-gradient(135deg, #451a03 0%, #9a3412 50%, #fed7aa 100%)',
    colors: ['#451a03', '#fed7aa'],
    textColor: '#ffedd5',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🍁', '🌽', '✨', '🕯️'],
    shape: 'circle',
    border: '#f59e0b',
    festivals: ['Thanksgiving']
  },

  // ==================== GENERAL THEMES ====================
  {
    id: 'festive',
    name: 'Festive Celebration',
    category: 'General · Vibrant & Party',
    styleType: 'vibrant',
    background: 'linear-gradient(135deg,#ff8a72,#fff0bd)',
    colors: ['#ff8a72', '#fff0bd'],
    textColor: '#7c2031',
    font: 'display',
    stickers: ['🎂', '🎈', '🎉', '✨'],
    shape: 'soft',
    border: '#fb7185'
  },
  {
    id: 'royal',
    name: 'Elegant Gold & Royal',
    category: 'General · Luxury & Royal',
    styleType: 'royal',
    background: 'linear-gradient(135deg,#071426,#1e2950)',
    colors: ['#071426', '#1e2950'],
    textColor: '#f7dfa0',
    font: 'serif',
    stickers: ['💍', '✨', '👑', '🥂'],
    shape: 'square',
    border: '#d8aa54'
  },
  {
    id: 'warm',
    name: 'Warm Minimalist',
    category: 'General · Clean & Pastel',
    styleType: 'minimal',
    background: 'linear-gradient(135deg,#f7e5df,#d8967b)',
    colors: ['#f7e5df', '#d8967b'],
    textColor: '#553b39',
    font: 'serif',
    stickers: ['🌸', '💕', '🌿', '🕊️'],
    shape: 'circle',
    border: '#b87161'
  },
  {
    id: 'fun',
    name: 'Candid & Fun',
    category: 'General · Bright & Playful',
    styleType: 'vibrant',
    background: 'linear-gradient(135deg,#5eead4,#fde047)',
    colors: ['#5eead4', '#fde047'],
    textColor: '#075985',
    font: 'sans',
    stickers: ['🥳', '🎁', '🎈', '🚀'],
    shape: 'pill',
    border: '#0ea5e9'
  },
  {
    id: 'midnight',
    name: 'Midnight Sparkle',
    category: 'General · Dark & Neon',
    styleType: 'royal',
    background: 'linear-gradient(135deg,#210635,#701a75)',
    colors: ['#210635', '#701a75'],
    textColor: '#f9a8d4',
    font: 'sans',
    stickers: ['🌟', '🎆', '🥂', '💖'],
    shape: 'heavy',
    border: '#e879f9'
  }
];

const FONT_MAP = {
  sans: 'Inter, Arial, sans-serif',
  serif: 'Georgia, serif',
  script: '"Brush Script MT", cursive',
  hand: '"Comic Sans MS", cursive',
  display: 'Impact, Arial Black, sans-serif'
};

const STICKERS = [
  '🎂', '🧁', '🕯️', '🎈', '🎉', '🥳', '💍', '💕', '🌸', '👶', '🍼', '🌟',
  '🥂', '👑', '🏆', '🪔', '🪁', '🌈', '☀️', '💃', '🦚', '🪈', '🏹', '🐘',
  '🌾', '🌺', '🌙', '🎄', '⭐', '❄️', '🌹', '💖', '🇮🇳', '🕊️', '🍁', '🌽', '🍯'
];
