const PRESET_TEMPLATES = [
  // ==================== RAKSHA BANDHAN ====================
  {
    id: 'rakhi-poster',
    name: 'Raksha Bandhan A Bond That Cares',
    category: 'Raksha Bandhan · Health & Bonding Poster',
    festival: 'Raksha Bandhan',
    styleType: 'poster',
    badge: 'SACRED SIBLING BOND',
    subtitle: 'A Bond That Cares',
    tagline: 'A thread of love, a lifetime of care and protection.',
    image: 'assets/festival/raksha-bandhan.jpg',
    pillars: [
      { icon: '🤝', title: 'CARE', desc: 'For Each Other' },
      { icon: '🥗', title: 'EAT', desc: 'Healthy Together' },
      { icon: '🏃', title: 'STAY', desc: 'Active & Fit' },
      { icon: '❤️', title: 'SUPPORT', desc: 'Always & Forever' }
    ],
    background: 'linear-gradient(175deg, #7c2d12 0%, #9a3412 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #7c2d12, #c2410c)',
    bodyBg: '#fffdfa',
    colors: ['#7c2d12', '#f97316'],
    textColor: '#431407',
    headerTextColor: '#ffedd5',
    accentColor: '#ea580c',
    font: 'sans',
    stickers: ['🪔', '✨', '🌸', '🪔'],
    shape: 'circle',
    border: '#ea580c',
    panel: true,
    festivals: ['Raksha Bandhan']
  },
  {
    id: 'rakhi-royal',
    name: 'Raksha Bandhan Sacred Silk & Gold',
    category: 'Raksha Bandhan · Royal Traditional Art',
    festival: 'Raksha Bandhan',
    styleType: 'royal',
    badge: 'SACRED BOND & RAKHI',
    subtitle: 'Lifelong Love & Protection',
    tagline: 'May this pious thread safeguard our happiness and cherish our bond forever.',
    image: 'assets/festival/raksha-bandhan.jpg',
    background: 'linear-gradient(145deg, #450a0a 0%, #78350f 50%, #1c0606 100%)',
    colors: ['#450a0a', '#fbbf24'],
    textColor: '#fffdfa',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🪔', '✨', '👑', '💖'],
    shape: 'soft',
    border: '#fbbf24',
    panel: true,
    festivals: ['Raksha Bandhan']
  },
  {
    id: 'rakhi-floral',
    name: 'Rakhi Sibling Sweetness & Joy',
    category: 'Raksha Bandhan · Joyful Festive Art',
    festival: 'Raksha Bandhan',
    styleType: 'vibrant',
    badge: 'CHERISHED SIBLING JOY',
    subtitle: 'Always by Your Side',
    tagline: 'Growing up with you is the greatest gift. Wishing you endless happiness.',
    image: 'assets/festival/raksha-bandhan.jpg',
    background: 'linear-gradient(135deg, #9a3412 0%, #ea580c 50%, #fef3c7 100%)',
    colors: ['#9a3412', '#fef3c7'],
    textColor: '#431407',
    headerTextColor: '#ffffff',
    accentColor: '#c2410c',
    font: 'serif',
    stickers: ['🌸', '💕', '✨', '🎁'],
    shape: 'soft',
    border: '#f97316',
    panel: true,
    festivals: ['Raksha Bandhan']
  },

  // ==================== DIWALI ====================
  {
    id: 'diwali-poster',
    name: 'Diwali Safe & Health Poster',
    category: 'Diwali · Poster Infographic',
    festival: 'Diwali',
    styleType: 'poster',
    badge: 'FESTIVAL OF LIGHTS',
    subtitle: 'Festival of Lights & Joy',
    tagline: 'May a thousand diyas light up your home with joy, prosperity and togetherness.',
    image: 'assets/festival/diwali.jpg',
    pillars: [
      { icon: '🛡️', title: 'PREVENT', desc: 'Burns & Fire' },
      { icon: '👂', title: 'PROTECT', desc: 'Your Hearing' },
      { icon: '🍃', title: 'BREATHE', desc: 'Clean Air' },
      { icon: '🥗', title: 'EAT RIGHT', desc: 'Enjoy Sweets' }
    ],
    background: 'linear-gradient(175deg, #180928 0%, #35104a 45%, #fff9f0 45.1%, #fff9f0 100%)',
    headerBg: 'linear-gradient(135deg, #180928, #3b0f55)',
    bodyBg: '#fffaf3',
    colors: ['#180928', '#ffaa00'],
    textColor: '#1e112a',
    headerTextColor: '#ffeedd',
    accentColor: '#d97706',
    font: 'sans',
    stickers: ['🪔', '✨', '🎆', '🌟'],
    shape: 'soft',
    border: '#f59e0b',
    panel: true,
    festivals: ['Diwali']
  },
  {
    id: 'diwali-royal',
    name: 'Diwali Royal Deepawali',
    category: 'Diwali · Luxury & Gold Art',
    festival: 'Diwali',
    styleType: 'royal',
    badge: 'ROYAL ILLUMINATION',
    subtitle: 'Festival of Divine Lights & Prosperity',
    tagline: 'May golden lamps illuminate every corner of your home and heart with peace.',
    image: 'assets/festival/diwali.jpg',
    background: 'radial-gradient(ellipse at 50% 25%, #4a192c 0%, #170414 70%, #0c020b 100%)',
    colors: ['#300d1d', '#facc15'],
    textColor: '#fffdfa',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🪔', '✨', '👑', '🪔'],
    shape: 'circle',
    border: '#d97706',
    panel: true,
    festivals: ['Diwali']
  },
  {
    id: 'diwali-vibrant',
    name: 'Diwali Rangoli & Spark',
    category: 'Diwali · Festive Amber Art',
    festival: 'Diwali',
    styleType: 'vibrant',
    badge: 'FESTIVE GLOW',
    subtitle: 'Joyous Auspicious Celebrations',
    tagline: 'Sparkling lights, joyous moments and sweet blessings all around.',
    image: 'assets/festival/diwali.jpg',
    background: 'linear-gradient(145deg, #851d18 0%, #b45309 50%, #fef3c7 100%)',
    colors: ['#851d18', '#fef3c7'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#b45309',
    font: 'serif',
    stickers: ['🪔', '🎆', '🌸', '✨'],
    shape: 'soft',
    border: '#fbbf24',
    panel: true,
    festivals: ['Diwali']
  },

  // ==================== HOLI ====================
  {
    id: 'holi-poster',
    name: 'Holi Play Safe & Stay Healthy',
    category: 'Holi · Poster Infographic',
    festival: 'Holi',
    styleType: 'poster',
    badge: 'FESTIVAL OF COLORS',
    subtitle: 'Rang Barse — Joy & Laughter',
    tagline: 'May every color you play with bring more joy, laughter and love into your life.',
    image: 'assets/festival/holi.jpg',
    pillars: [
      { icon: '🧴', title: 'PROTECT', desc: 'Your Skin' },
      { icon: '👓', title: 'PROTECT', desc: 'Your Eyes' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🤝', title: 'PLAY SAFE', desc: 'Be Respectful' }
    ],
    background: 'linear-gradient(175deg, #ec4899 0%, #8b5cf6 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #db2777, #7c3aed)',
    bodyBg: '#fffdfa',
    colors: ['#db2777', '#06b6d4'],
    textColor: '#3b0764',
    headerTextColor: '#ffffff',
    accentColor: '#ec4899',
    font: 'sans',
    stickers: ['🌈', '🎉', '🌸', '✨'],
    shape: 'heavy',
    border: '#a855f7',
    panel: true,
    festivals: ['Holi']
  },
  {
    id: 'holi-vibrant',
    name: 'Holi Gulal Explosion',
    category: 'Holi · Ultra Vibrant Splash Art',
    festival: 'Holi',
    styleType: 'vibrant',
    badge: 'COLOR CARNIVAL',
    subtitle: 'Rang Barse — Joy & Laughter',
    tagline: 'Drenched in friendship, colors, music and pure happiness.',
    image: 'assets/festival/holi.jpg',
    background: 'radial-gradient(circle at 80% 20%, #f43f5e 0%, #ec4899 30%, #8b5cf6 65%, #06b6d4 100%)',
    colors: ['#f43f5e', '#06b6d4'],
    textColor: '#ffffff',
    headerTextColor: '#ffffff',
    accentColor: '#fde047',
    font: 'display',
    stickers: ['🎨', '💦', '🌈', '🥳'],
    shape: 'pill',
    border: '#f43f5e',
    panel: true,
    festivals: ['Holi']
  },

  // ==================== NAVRATRI ====================
  {
    id: 'navratri-poster',
    name: 'Navratri Dance & Good Health',
    category: 'Navratri · Poster Infographic',
    festival: 'Navratri',
    styleType: 'poster',
    badge: 'NINE NIGHTS OF DEVOTION',
    subtitle: 'Dance • Devotion • Divine Joy',
    tagline: 'May every beat of the dandiya fill your nine nights with joy and blessings.',
    image: 'assets/festival/navratri.jpg',
    imageFocusY: 20,
    pillars: [
      { icon: '🏃', title: 'WARM UP', desc: 'Before Dance' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '👟', title: 'WEAR', desc: 'Right Footwear' },
      { icon: '🛌', title: 'REST &', desc: 'Recover Well' }
    ],
    background: 'linear-gradient(175deg, #4c0519 0%, #831843 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #4c0519, #9d174d)',
    bodyBg: '#fffdfa',
    colors: ['#4c0519', '#fbbf24'],
    textColor: '#3b0764',
    headerTextColor: '#fef3c7',
    accentColor: '#db2777',
    font: 'sans',
    stickers: ['💃', '🪔', '✨', '🌸'],
    shape: 'circle',
    border: '#f59e0b',
    panel: true,
    festivals: ['Navratri']
  },
  {
    id: 'navratri-royal',
    name: 'Navratri Garba Raas Glow',
    category: 'Navratri · Royal Garba Art',
    festival: 'Navratri',
    styleType: 'royal',
    badge: 'DANDIYA NIGHTS',
    subtitle: 'Nine Nights of Divine Radiance',
    tagline: 'Whirling beats, joyful smiles, and Maa Durga divine blessings.',
    image: 'assets/festival/navratri.jpg',
    imageFocusY: 20,
    background: 'linear-gradient(145deg, #2e1065 0%, #581c87 50%, #9333ea 100%)',
    colors: ['#2e1065', '#9333ea'],
    textColor: '#fffdfa',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🪔', '💃', '✨', '🥁'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['Navratri']
  },

  // ==================== UTTARAYAN ====================
  {
    id: 'uttarayan-poster',
    name: 'Uttarayan Fly High, Stay Safe',
    category: 'Uttarayan · Poster Infographic',
    festival: 'Uttarayan / Makar Sankranti',
    styleType: 'poster',
    badge: 'KITE FESTIVAL OF JOY',
    subtitle: 'Fly High, Celebrate Free',
    tagline: 'May your kites soar high and your joys fly even higher this Uttarayan.',
    image: 'assets/festival/uttarayan.jpg',
    imageFocusY: 35,
    pillars: [
      { icon: '🧢', title: 'PROTECT', desc: 'From Sun & UV' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🏢', title: 'BE SAFE', desc: 'On Terrace' },
      { icon: '🕊️', title: 'PROTECT', desc: 'Eyes & Birds' }
    ],
    background: 'linear-gradient(175deg, #0284c7 0%, #0369a1 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #0284c7, #075985)',
    bodyBg: '#fffdfa',
    colors: ['#0284c7', '#fbbf24'],
    textColor: '#0c4a6e',
    headerTextColor: '#f0f9ff',
    accentColor: '#0284c7',
    font: 'sans',
    stickers: ['🪁', '☀️', '🎉', '✨'],
    shape: 'soft',
    border: '#38bdf8',
    panel: true,
    festivals: ['Uttarayan / Makar Sankranti']
  },
  {
    id: 'uttarayan-azure',
    name: 'Uttarayan Azure Sky Carnival',
    category: 'Uttarayan · Sky & Kites Art',
    festival: 'Uttarayan / Makar Sankranti',
    styleType: 'vibrant',
    badge: 'KAI PO CHE SKY',
    subtitle: 'Soaring Hopes, Unlimited Joy',
    tagline: 'Loud cheers, colorful flying kites, and chikki sweetness.',
    image: 'assets/festival/uttarayan.jpg',
    imageFocusY: 35,
    background: 'linear-gradient(160deg, #0369a1 0%, #0284c7 50%, #38bdf8 100%)',
    colors: ['#0369a1', '#38bdf8'],
    textColor: '#f0f9ff',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'sans',
    stickers: ['🪁', '☀️', '🪁', '✨'],
    shape: 'pill',
    border: '#0284c7',
    panel: true,
    festivals: ['Uttarayan / Makar Sankranti']
  },

  // ==================== JANMASHTAMI ====================
  {
    id: 'janmashtami-poster',
    name: 'Janmashtami Joy & Healthy Devotion',
    category: 'Janmashtami · Poster Infographic',
    festival: 'Janmashtami',
    styleType: 'poster',
    badge: 'KRISHNA JANMOTSAV',
    subtitle: 'Celebrate with Devotion & Joy',
    tagline: "May Kanha's blessings bring joy, peace and divine grace to your life.",
    image: 'assets/festival/janmashtami.jpg',
    pillars: [
      { icon: '🥛', title: 'EAT SAFE', desc: 'Keep Fasting Pure' },
      { icon: '💧', title: 'STAY', desc: 'Hydrated' },
      { icon: '🥗', title: 'CHOOSE', desc: 'Healthy Fast Food' },
      { icon: '🧘', title: 'REST &', desc: 'Meditate' }
    ],
    background: 'linear-gradient(175deg, #1e3a8a 0%, #172554 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #1e3a8a, #1d4ed8)',
    bodyBg: '#fffdfa',
    colors: ['#1e3a8a', '#fbbf24'],
    textColor: '#172554',
    headerTextColor: '#eff6ff',
    accentColor: '#2563eb',
    font: 'sans',
    stickers: ['🪈', '🦚', '✨', '🌸'],
    shape: 'circle',
    border: '#2563eb',
    panel: true,
    festivals: ['Janmashtami']
  },
  {
    id: 'janmashtami-divine',
    name: 'Janmashtami Peacock Radiance',
    category: 'Janmashtami · Peacock Blue & Gold Art',
    festival: 'Janmashtami',
    styleType: 'royal',
    badge: 'DIVINE FLUTE & PEACOCK',
    subtitle: 'Krishna Janmotsav Blessings',
    tagline: 'May Kanha bless your life with bliss, peace and divine melody.',
    image: 'assets/festival/janmashtami.jpg',
    background: 'radial-gradient(ellipse at center, #0f2b5c 0%, #081734 70%, #030a18 100%)',
    colors: ['#0f2b5c', '#030a18'],
    textColor: '#fffdfa',
    headerTextColor: '#fef08a',
    accentColor: '#facc15',
    font: 'serif',
    stickers: ['🦚', '🪈', '✨', '👑'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['Janmashtami']
  },

  // ==================== GANESH CHATURTHI ====================
  {
    id: 'ganesh-poster',
    name: 'Ganesh Chaturthi Responsible Poster',
    category: 'Ganesh Chaturthi · Poster Infographic',
    festival: 'Ganesh Chaturthi',
    styleType: 'poster',
    badge: 'GANPATI BAPPA MORYA',
    subtitle: 'Wisdom, Prosperity & Joy',
    tagline: 'May Bappa remove every obstacle and bring joy and blessings to your home.',
    image: 'assets/festival/ganesh.jpg',
    pillars: [
      { icon: '🌱', title: 'CHOOSE', desc: 'Eco-Friendly Idols' },
      { icon: '🧹', title: 'KEEP', desc: 'Clean Everywhere' },
      { icon: '🥟', title: 'EAT', desc: 'Healthy Modaks' },
      { icon: '🛡️', title: 'STAY', desc: 'Safe in Crowds' }
    ],
    background: 'linear-gradient(175deg, #7c2d12 0%, #c2410c 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #7c2d12, #ea580c)',
    bodyBg: '#fffdfa',
    colors: ['#7c2d12', '#fbbf24'],
    textColor: '#431407',
    headerTextColor: '#fff7ed',
    accentColor: '#ea580c',
    font: 'sans',
    stickers: ['🐘', '🪔', '✨', '🌺'],
    shape: 'soft',
    border: '#f97316',
    panel: true,
    festivals: ['Ganesh Chaturthi']
  },
  {
    id: 'ganesh-royal',
    name: 'Ganesh Siddhivinayak Gold',
    category: 'Ganesh Chaturthi · Saffron & Crimson Art',
    festival: 'Ganesh Chaturthi',
    styleType: 'royal',
    badge: 'VIGHNAHARTA BLESSINGS',
    subtitle: 'Wisdom, Auspiciousness & Joy',
    tagline: 'May Lord Ganesha remove all obstacles and shower prosperity upon your family.',
    image: 'assets/festival/ganesh.jpg',
    background: 'linear-gradient(145deg, #9a3412 0%, #ea580c 50%, #fef08a 100%)',
    colors: ['#9a3412', '#fef08a'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#ea580c',
    font: 'serif',
    stickers: ['🪔', '🌺', '✨', '👑'],
    shape: 'circle',
    border: '#f59e0b',
    panel: true,
    festivals: ['Ganesh Chaturthi']
  },

  // ==================== DUSSEHRA ====================
  {
    id: 'dussehra-poster',
    name: 'Dussehra Victory & Wellness Poster',
    category: 'Dussehra · Poster Infographic',
    festival: 'Dussehra',
    styleType: 'poster',
    badge: 'VICTORY OVER EVIL',
    subtitle: 'Victory of Good Over Evil',
    tagline: 'Let’s win over negativity and be the best version of ourselves.',
    image: 'assets/festival/dussehra.jpg',
    pillars: [
      { icon: '🌱', title: 'CHOOSE', desc: 'Good Habits' },
      { icon: '🧘', title: 'MANAGE', desc: 'Stress & Stay Calm' },
      { icon: '💪', title: 'STAY', desc: 'Active & Strong' },
      { icon: '👨‍👩‍👧‍👦', title: 'SPEND TIME', desc: 'With Family' }
    ],
    background: 'linear-gradient(175deg, #831843 0%, #9f1239 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #831843, #be123c)',
    bodyBg: '#fffdfa',
    colors: ['#831843', '#facc15'],
    textColor: '#4c0519',
    headerTextColor: '#fff1f2',
    accentColor: '#e11d48',
    font: 'sans',
    stickers: ['🏹', '🪔', '✨', '🌟'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Dussehra']
  },
  {
    id: 'dussehra-royal',
    name: 'Dussehra Vijayadashami Glory',
    category: 'Dussehra · Warrior Amber Art',
    festival: 'Dussehra',
    styleType: 'royal',
    badge: 'TRIUMPH OF LIGHT',
    subtitle: 'Auspicious New Beginnings',
    tagline: 'May truth and righteousness guide your path to victory.',
    image: 'assets/festival/dussehra.jpg',
    background: 'linear-gradient(135deg, #450a0a 0%, #7f1d1d 50%, #f59e0b 100%)',
    colors: ['#450a0a', '#f59e0b'],
    textColor: '#fffdfa',
    headerTextColor: '#fef08a',
    accentColor: '#f59e0b',
    font: 'serif',
    stickers: ['🏹', '👑', '✨', '🪔'],
    shape: 'square',
    border: '#d97706',
    panel: true,
    festivals: ['Dussehra']
  },

  // ==================== BESTU VARAS ====================
  {
    id: 'bestuvaras-poster',
    name: 'Bestu Varas New Beginnings Poster',
    category: 'Bestu Varas · Poster Infographic',
    festival: 'Bestu Varas (Gujarati New Year)',
    styleType: 'poster',
    badge: 'GUJARATI NEW YEAR',
    subtitle: 'New Beginnings, Fresh Joy',
    tagline: 'May this new year bring prosperity, happiness and togetherness to your family.',
    image: 'assets/festival/bestu-varas.jpg',
    pillars: [
      { icon: '🥗', title: 'EAT', desc: 'Balanced Diet' },
      { icon: '🏃', title: 'MOVE', desc: 'Daily & Stay Fit' },
      { icon: '✨', title: 'THINK', desc: 'Positive & Happy' },
      { icon: '📋', title: 'PLAN', desc: 'Your Health' }
    ],
    background: 'linear-gradient(175deg, #14532d 0%, #15803d 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #14532d, #16a34a)',
    bodyBg: '#fffdfa',
    colors: ['#14532d', '#facc15'],
    textColor: '#052e16',
    headerTextColor: '#f0fdf4',
    accentColor: '#16a34a',
    font: 'sans',
    stickers: ['🪔', '🌿', '✨', '🌸'],
    shape: 'circle',
    border: '#22c55e',
    panel: true,
    festivals: ['Bestu Varas (Gujarati New Year)']
  },
  {
    id: 'bestuvaras-royal',
    name: 'Nutan Varshabhinandan Gold',
    category: 'Bestu Varas · Auspicious Gold & Saffron Art',
    festival: 'Bestu Varas (Gujarati New Year)',
    styleType: 'royal',
    badge: 'NUTAN VARSHABHINANDAN',
    subtitle: 'Auspicious Gujarati New Year Wishes',
    tagline: 'May this year overflow with happiness, peace and success.',
    image: 'assets/festival/bestu-varas.jpg',
    background: 'linear-gradient(145deg, #78350f 0%, #b45309 50%, #fef3c7 100%)',
    colors: ['#78350f', '#fef3c7'],
    textColor: '#451a03',
    headerTextColor: '#ffffff',
    accentColor: '#d97706',
    font: 'serif',
    stickers: ['🪔', '🌾', '✨', '👑'],
    shape: 'soft',
    border: '#f59e0b',
    panel: true,
    festivals: ['Bestu Varas (Gujarati New Year)']
  },

  // ==================== INDEPENDENCE & REPUBLIC DAY ====================
  {
    id: 'independence-poster',
    name: 'Independence Day Freedom & Health',
    category: 'Independence Day · Poster Infographic',
    festival: 'Independence Day',
    styleType: 'poster',
    badge: 'PROUD & FREE',
    subtitle: 'Freedom • Unity • Pride',
    tagline: 'Celebrating the spirit of freedom, unity and pride in our nation.',
    image: 'assets/festival/independence.jpg',
    pillars: [
      { icon: '🏃', title: 'STAY', desc: 'Active & Energetic' },
      { icon: '🥗', title: 'EAT', desc: 'Balanced Food' },
      { icon: '🇮🇳', title: 'KEEP INDIA', desc: 'Clean & Green' },
      { icon: '🤝', title: 'CARE', desc: 'For All Citizens' }
    ],
    background: 'linear-gradient(175deg, #c2410c 0%, #15803d 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #ea580c, #16a34a)',
    bodyBg: '#fffdfa',
    colors: ['#ea580c', '#16a34a'],
    textColor: '#1e293b',
    headerTextColor: '#ffffff',
    accentColor: '#0284c7',
    font: 'sans',
    stickers: ['🇮🇳', '🕊️', '✨', '🌟'],
    shape: 'soft',
    border: '#0284c7',
    panel: true,
    festivals: ['Independence Day', 'Republic Day']
  },

  // ==================== VALENTINE'S DAY ====================
  {
    id: 'valentines-poster',
    name: 'Valentine’s Connection & Wellbeing',
    category: 'Valentine\'s Day · Poster Infographic',
    festival: 'Valentine\'s Day',
    styleType: 'poster',
    badge: 'CELEBRATE LOVE',
    subtitle: 'Love • Connection • Joy',
    tagline: 'May your bond grow deeper and sweeter with every passing day.',
    image: 'assets/festival/valentine.jpg',
    pillars: [
      { icon: '💬', title: 'CONNECT', desc: 'Talk & Listen' },
      { icon: '❤️', title: 'CARE', desc: 'For Each Other' },
      { icon: '⏳', title: 'SPEND TIME', desc: 'Together' },
      { icon: '🌸', title: 'BE KIND', desc: 'Every Day' }
    ],
    background: 'linear-gradient(175deg, #881337 0%, #be123c 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #881337, #e11d48)',
    bodyBg: '#fffdfa',
    colors: ['#881337', '#f43f5e'],
    textColor: '#4c0519',
    headerTextColor: '#ffe4e6',
    accentColor: '#e11d48',
    font: 'sans',
    stickers: ['❤️', '💕', '🌹', '✨'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Valentine\'s Day']
  },
  {
    id: 'valentines-romantic',
    name: 'Valentine Velvet Rose Romance',
    category: 'Valentine\'s Day · Romantic Luxury Art',
    festival: 'Valentine\'s Day',
    styleType: 'royal',
    badge: 'ENDLESS LOVE',
    subtitle: 'Heart to Heart, Forever',
    tagline: 'You make every ordinary moment feel extraordinary and magical.',
    image: 'assets/festival/valentine.jpg',
    background: 'linear-gradient(145deg, #4c0519 0%, #9f1239 50%, #fda4af 100%)',
    colors: ['#4c0519', '#fda4af'],
    textColor: '#fffdfa',
    headerTextColor: '#ffffff',
    accentColor: '#fb7185',
    font: 'serif',
    stickers: ['🌹', '💖', '✨', '🥂'],
    shape: 'soft',
    border: '#f43f5e',
    panel: true,
    festivals: ['Valentine\'s Day']
  },

  // ==================== CHRISTMAS ====================
  {
    id: 'christmas-poster',
    name: 'Christmas Joy & Health Poster',
    category: 'Christmas · Poster Infographic',
    festival: 'Christmas',
    styleType: 'poster',
    badge: 'SEASON OF JOY',
    subtitle: 'Joy • Peace • Togetherness',
    tagline: 'May the warmth of Christmas fill your home with joy and togetherness.',
    image: 'assets/festival/christmas.jpg',
    pillars: [
      { icon: '🥗', title: 'EAT', desc: 'Mindfully & Light' },
      { icon: '🎁', title: 'SHARE', desc: 'Kindness & Love' },
      { icon: '🏃', title: 'STAY', desc: 'Active & Warm' },
      { icon: '🛌', title: 'REST', desc: 'Well & Recharge' }
    ],
    background: 'linear-gradient(175deg, #0f172a 0%, #1e293b 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #0f172a, #166534)',
    bodyBg: '#fffdfa',
    colors: ['#0f172a', '#166534'],
    textColor: '#0f172a',
    headerTextColor: '#f8fafc',
    accentColor: '#dc2626',
    font: 'sans',
    stickers: ['🎄', '⭐', '🎁', '✨'],
    shape: 'soft',
    border: '#22c55e',
    panel: true,
    festivals: ['Christmas']
  },

  // ==================== EID ====================
  {
    id: 'eid-poster',
    name: 'Eid Mubarak Peace & Health',
    category: 'Eid · Poster Infographic',
    festival: 'Eid',
    styleType: 'poster',
    badge: 'PEACE & GRATITUDE',
    subtitle: 'Peace • Gratitude • Blessings',
    tagline: 'May Eid bring peace, gratitude and warm togetherness.',
    image: 'assets/festival/eid.svg',
    pillars: [
      { icon: '🤲', title: 'SHARE', desc: 'Blessings & Care' },
      { icon: '🥗', title: 'EAT', desc: 'Mindfully' },
      { icon: '👨‍👩‍👧‍👦', title: 'SPEND', desc: 'Family Time' },
      { icon: '✨', title: 'SPREAD', desc: 'Kindness Everywhere' }
    ],
    background: 'linear-gradient(175deg, #064e3b 0%, #047857 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #064e3b, #059669)',
    bodyBg: '#fffdfa',
    colors: ['#064e3b', '#facc15'],
    textColor: '#022c22',
    headerTextColor: '#ecfdf5',
    accentColor: '#059669',
    font: 'sans',
    stickers: ['🌙', '✨', '💐', '🤲'],
    shape: 'circle',
    border: '#10b981',
    panel: true,
    festivals: ['Eid']
  },

  // ==================== NEW YEAR ====================
  {
    id: 'newyear-poster',
    name: 'New Year Goals & Health',
    category: 'New Year · Poster Infographic',
    festival: 'New Year',
    styleType: 'poster',
    badge: 'FRESH BEGINNINGS',
    subtitle: 'New Chapter • Fresh Beginnings',
    tagline: 'Step into the new year with hope, happiness and new beginnings.',
    image: 'assets/festival/newyear.svg',
    pillars: [
      { icon: '🎯', title: 'SET', desc: 'Daily Habits' },
      { icon: '🏃', title: 'MOVE', desc: 'Every Single Day' },
      { icon: '🧠', title: 'STAY', desc: 'Mindful & Positive' },
      { icon: '💖', title: 'CHERISH', desc: 'Friends & Family' }
    ],
    background: 'linear-gradient(175deg, #18181b 0%, #27272a 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #09090b, #27272a)',
    bodyBg: '#fffdfa',
    colors: ['#18181b', '#facc15'],
    textColor: '#18181b',
    headerTextColor: '#fef08a',
    accentColor: '#eab308',
    font: 'sans',
    stickers: ['🎆', '🥂', '🌟', '✨'],
    shape: 'soft',
    border: '#eab308',
    panel: true,
    festivals: ['New Year']
  },

  // ==================== THANKSGIVING ====================
  {
    id: 'thanksgiving-poster',
    name: 'Thanksgiving Harvest Poster',
    category: 'Thanksgiving · Poster Infographic',
    festival: 'Thanksgiving',
    styleType: 'poster',
    badge: 'HARVEST OF GRATITUDE',
    subtitle: 'Gratitude • Family • Togetherness',
    tagline: 'May your table be full and your heart even fuller this Thanksgiving.',
    image: 'assets/festival/thanksgiving.svg',
    imageFocusY: 82,
    background: 'linear-gradient(175deg, #7c2d12 0%, #9a3412 45%, #fffdfa 45.1%, #fffdfa 100%)',
    headerBg: 'linear-gradient(135deg, #7c2d12, #c2410c)',
    bodyBg: '#fffdfa',
    colors: ['#7c2d12', '#f2c14e'],
    textColor: '#5c2e0e',
    headerTextColor: '#fef3c7',
    accentColor: '#c2410c',
    font: 'serif',
    stickers: ['🍂', '🍁', '🌽', '🥧'],
    shape: 'soft',
    border: '#c2410c',
    panel: true,
    festivals: ['Thanksgiving']
  },
  {
    id: 'thanksgiving-minimal',
    name: 'Thanksgiving Warm Gratitude',
    category: 'Thanksgiving · Minimal Harvest Art',
    festival: 'Thanksgiving',
    styleType: 'minimal',
    subtitle: 'Gratitude • Family • Togetherness',
    tagline: 'Grateful for you, today and always.',
    image: 'assets/festival/thanksgiving.svg',
    imageFocusY: 82,
    compactArt: true,
    background: 'linear-gradient(160deg, #fdf6e8 0%, #f3dfb8 100%)',
    colors: ['#fdf6e8', '#c2410c'],
    textColor: '#5c2e0e',
    headerTextColor: '#fef3c7',
    accentColor: '#c2410c',
    font: 'serif',
    stickers: ['🍂', '🌾', '🍁', '🧡'],
    shape: 'soft',
    border: '#d97706',
    panel: true,
    festivals: ['Thanksgiving']
  },

  // ==================== GENERAL THEMES ====================
  {
    id: 'festive',
    name: 'Festive Celebration',
    category: 'General · Vibrant & Party',
    styleType: 'vibrant',
    background: 'linear-gradient(135deg,#ff8a72,#fff0bd)',
    colors: ['#ff8a72', '#fff0bd'],
    textColor: '#7c2031',
    font: 'display',
    stickers: ['🎂', '🎈', '🎉', '✨'],
    shape: 'soft',
    border: '#fb7185'
  },
  {
    id: 'royal',
    name: 'Elegant Gold & Royal',
    category: 'General · Luxury & Royal',
    styleType: 'royal',
    background: 'linear-gradient(135deg,#071426,#1e2950)',
    colors: ['#071426', '#1e2950'],
    textColor: '#f7dfa0',
    font: 'serif',
    stickers: ['💍', '✨', '👑', '🥂'],
    shape: 'square',
    border: '#d8aa54'
  },
  {
    id: 'warm',
    name: 'Warm Minimalist',
    category: 'General · Clean & Pastel',
    styleType: 'minimal',
    background: 'linear-gradient(135deg,#f7e5df,#d8967b)',
    colors: ['#f7e5df', '#d8967b'],
    textColor: '#553b39',
    font: 'serif',
    stickers: ['🌸', '💕', '🌿', '🕊️'],
    shape: 'circle',
    border: '#b87161'
  },
  {
    id: 'fun',
    name: 'Candid & Fun',
    category: 'General · Bright & Playful',
    styleType: 'vibrant',
    background: 'linear-gradient(135deg,#5eead4,#fde047)',
    colors: ['#5eead4', '#fde047'],
    textColor: '#075985',
    font: 'sans',
    stickers: ['🥳', '🎁', '🎈', '🚀'],
    shape: 'pill',
    border: '#0ea5e9'
  },
  {
    id: 'midnight',
    name: 'Midnight Sparkle',
    category: 'General · Dark & Neon',
    styleType: 'royal',
    background: 'linear-gradient(135deg,#210635,#701a75)',
    colors: ['#210635', '#701a75'],
    textColor: '#f9a8d4',
    font: 'sans',
    stickers: ['🌟', '🎆', '🥂', '💖'],
    shape: 'heavy',
    border: '#e879f9'
  }
];

const FONT_MAP = {
  sans: 'Inter, Arial, sans-serif',
  serif: 'Georgia, serif',
  script: '"Brush Script MT", cursive',
  hand: '"Comic Sans MS", cursive',
  display: 'Impact, Arial Black, sans-serif'
};

const STICKERS = [
  '🎂', '🧁', '🕯️', '🎈', '🎉', '🥳', '💍', '💕', '🌸', '👶', '🍼', '🌟',
  '🥂', '👑', '🏆', '🪔', '🪁', '🌈', '☀️', '💃', '🦚', '🪈', '🏹', '🐘',
  '🌾', '🌺', '🌙', '🎄', '⭐', '❄️', '🌹', '💖', '🇮🇳', '🕊️'
];
