const CACHE='wishcraft-v22';
// Precache the app shell plus only the festival images templates.js actually references
// (each festival also has unused legacy .svg/.png duplicates on disk from earlier iterations;
// those are intentionally left out of install-time precache and are runtime-cached on demand
// by the fetch handler below if anything ever requests them).
const APP=['./','./index.html','./css/styles.css','./css/fixes.css','./js/messages.js','./js/templates.js','./js/app.js','./manifest.json','./assets/icon.svg','./assets/icons/icon-192.png','./assets/icons/icon-512.png','./assets/icons/icon-512-maskable.png','./assets/icons/favicon-48.png','./assets/icons/apple-touch-icon.png','./assets/festival/bestu-varas.jpg','./assets/festival/christmas.jpg','./assets/festival/diwali.jpg','./assets/festival/dussehra.jpg','./assets/festival/eid.svg','./assets/festival/ganesh.jpg','./assets/festival/holi.jpg','./assets/festival/independence.jpg','./assets/festival/janmashtami.jpg','./assets/festival/navratri.jpg','./assets/festival/newyear.svg','./assets/festival/raksha-bandhan.jpg','./assets/festival/thanksgiving.svg','./assets/festival/uttarayan.jpg','./assets/festival/valentine.jpg','./assets/birthday/birthday-elegant.jpg','./assets/birthday/birthday-bright.jpg'];
self.addEventListener('install',event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(APP)).then(()=>self.skipWaiting())));
self.addEventListener('activate',event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',event=>{if(event.request.method!=='GET')return;event.respondWith(fetch(event.request).then(response=>{if(response.ok&&new URL(event.request.url).origin===location.origin){const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(event.request).then(cached=>cached||caches.match('./index.html'))))});
